# Generated by Django 6.0.8 on 2026-09-27 22:18

import apps.users.models.user
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userevent_user_insert_insert_user_update_update_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=apps.users.models.user.language_choices, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='userevent',
            name='language',
            field=models.CharField(blank=True, choices=apps.users.models.user.language_choices, default='', max_length=15),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "language", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "username") VALUES (NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."language", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."username"); RETURN NULL;', hash='5d2619be4fc21d72ffebaf704271349bb60e80ab', operation='INSERT', pgid='pgtrigger_insert_insert_52e78', table='users_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "users_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "language", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "username") VALUES (NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."language", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."username"); RETURN NULL;', hash='6d31a5a5c43fde20c245741c7eaa643bad1e9cb9', operation='UPDATE', pgid='pgtrigger_update_update_16e22', table='users_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "users_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "language", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "username") VALUES (OLD."created_at", OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."language", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."username"); RETURN NULL;', hash='d8cc8232b294c431eaa42e7b0d6348340bd88c11', operation='DELETE', pgid='pgtrigger_delete_delete_56c96', table='users_user', when='AFTER')),
        ),
    ]
