/**
 * Placeholder - regenerate for real once the backend is running:
 *   npx openapi-typescript http://auth.<domain>/v0/openapi.yaml -o src/schema.ts
 * (allauth.headless serves its own spec when HEADLESS_SERVE_SPECIFICATION is on.)
 * This file was auto-generated by openapi-typescript. Do not make direct changes to the file.
 */

type User = {
  id: string
  username: string
  email: string
}

type Session = {
  id: number
  ip: string
  is_current: boolean
  user_agent: string
  created_at: number
  // Only present when USERSESSIONS_TRACK_ACTIVITY is on - off by default (see settings.py).
  last_seen_at?: number
}

type EmailAddress = { email: string; primary: boolean; verified: boolean }
type ProviderAccount = { id: number; provider: { id: string; name: string }; uid: string; display: { name: string } }

type Flow = { id: string; is_pending?: boolean; providers?: string[] }
type SessionData = { user: User; methods?: unknown[] }
type SessionMeta = { is_authenticated: boolean }
type SessionOk = { status: number; data: SessionData; meta: SessionMeta }
type SessionErr = { status: number; data?: { flows: Flow[] }; meta?: SessionMeta }
// allauth headless's flat validation-error shape ({errors: [{code, param, message}]}) - distinct
// from SessionErr, which is the 401 "pending flow" shape these 400s never take.
type ValidationErr = { status: number; errors: { code: string; param?: string; message: string }[] }

export interface paths {
  '/v0/browser/v1/auth/session': {
    get: { responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } } }
    delete: { responses: { 200: { content: { 'application/json': SessionOk } } } }
  }
  '/v0/browser/v1/auth/login': {
    post: {
      requestBody: { content: { 'application/json': { username?: string; email?: string; password: string } } }
      responses: { 200: { content: { 'application/json': SessionOk } }; 400: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/browser/v1/auth/signup': {
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password: string } } }
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/auth/password/request': {
    post: { requestBody: { content: { 'application/json': { email: string } } }; responses: { 200: { content: { 'application/json': unknown } } } }
  }
  '/v0/browser/v1/auth/password/reset': {
    post: {
      requestBody: { content: { 'application/json': { key: string; password: string } } }
      // 200 only if resetting the password also completes a pending login - otherwise a *valid*
      // key still comes back 401: password changed, but the session isn't authenticated until the
      // user logs in with it. Same shape as signup/email-verify.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/auth/email/verify': {
    post: {
      requestBody: { content: { 'application/json': { key: string } } }
      // 200 only if the verified email also completes a pending login (e.g. right after signup,
      // same session) - otherwise a *valid* key still comes back as 401: confirmed, but the
      // session isn't authenticated until the user logs in separately. Same shape as signup.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
  '/v0/browser/v1/account/password/change': {
    post: {
      requestBody: { content: { 'application/json': { current_password?: string; new_password: string } } }
      responses: { 200: { content: { 'application/json': unknown } } }
    }
  }
  '/v0/browser/v1/account/email': {
    get: { responses: { 200: { content: { 'application/json': { data: EmailAddress[] } } } } }
    post: {
      requestBody: { content: { 'application/json': { email: string } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
    put: { requestBody: { content: { 'application/json': { email: string } } }; responses: { 200: { content: { 'application/json': unknown } } } }
    patch: {
      requestBody: { content: { 'application/json': { email: string; primary: boolean } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
    delete: {
      requestBody: { content: { 'application/json': { email: string } } }
      responses: {
        200: { content: { 'application/json': { data: EmailAddress[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/browser/v1/account/providers': {
    get: { responses: { 200: { content: { 'application/json': { data: ProviderAccount[] } } } } }
    delete: {
      requestBody: { content: { 'application/json': { provider: string; account: string } } }
      responses: {
        200: { content: { 'application/json': { data: ProviderAccount[] } } }
        400: { content: { 'application/json': ValidationErr } }
      }
    }
  }
  '/v0/browser/v1/auth/sessions': {
    get: { responses: { 200: { content: { 'application/json': { status: number; data: Session[] } } } } }
    delete: {
      requestBody: { content: { 'application/json': { sessions: number[] } } }
      responses: {
        200: { content: { 'application/json': { status: number; data: Session[] } } }
        401: { content: { 'application/json': SessionErr } }
      }
    }
  }
  '/v0/browser/v1/auth/provider/signup': {
    // The pending sociallogin's suggested user/account, fetched to prefill the "finish setting
    // up your account" form (see CompleteSignupForm.tsx) - a 409 here means there's no pending
    // signup at all (this page was reached directly, not via a real provider redirect).
    get: {
      responses: {
        200: { content: { 'application/json': { status: number; data: { user: User } } } }
        409: { content: { 'application/json': unknown } }
      }
    }
    post: {
      requestBody: { content: { 'application/json': { username: string; email: string; password?: string } } }
      // 200 if this also completes login; 401 if the account was created but needs a separate
      // login (mandatory email verification) - same shape as signup itself.
      responses: { 200: { content: { 'application/json': SessionOk } }; 401: { content: { 'application/json': SessionErr } } }
    }
  }
}
